[versions]
accompanist = "0.37.3"
androidGradlePlugin = "9.0.1"
androidxComposeBom = "2026.02.00"
androidxCore = "1.17.0"
androidMaterial = "1.13.0"
androidxAppCompat = "1.7.1"
androidxActivity = "1.12.4"
graphics = "1.1.0"
constraintLayout = "1.1.1"

androidxLifecycle = "2.10.0"
androidxNavigation = "2.9.7"

androidxEspresso = "3.7.0"
androidxTestExt = "1.3.0"


coil = "2.7.0"

junit4 = "4.13.2"

kotlin = "2.3.10"

coroutines = "1.10.2"
datetime = "0.7.1"
serialization = "1.10.0"
okhttp = "5.3.2"

room = "2.8.4"
ksp = "2.3.6"

youtubedlAndroid = "0.18.1"

mmkv = "2.3.0"
# pin to v1.3.x for 32-bit support

koin = "4.1.1"

ktfmt = "0.25.0"

[libraries]


androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCore" }
android-material = { group = "com.google.android.material", name = "material", version.ref = "androidMaterial" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidxAppCompat" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidxActivity" }

androidx-lifecycle-runtimeCompose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidxLifecycle" }

accompanist-permissions = { group = "com.google.accompanist", name = "accompanist-permissions", version.ref = "accompanist" }

#androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidxComposeBom" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom-alpha", version.ref = "androidxComposeBom" }

androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
androidx-compose-material-iconsExtended = { group = "androidx.compose.material", name = "material-icons-extended" }
androidx-compose-animation = { group = "androidx.compose.animation", name = "animation" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }

androidx-compose-material = { group = "androidx.compose.material", name = "material" }

androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-material3-windowSizeClass = { group = "androidx.compose.material3", name = "material3-window-size-class" }

androidx-graphics-shapes = { group = "androidx.graphics", name = "graphics-shapes", version.ref = "graphics" }

okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }

androidx-documentfile = { group = "androidx.documentfile", name = "documentfile", version = "1.0.1" }

androidx-compose-runtime = { group = "androidx.compose.runtime", name = "runtime" }
androidx-compose-ui-test = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }

androidx-constraintlayout-compose = { group = "androidx.constraintlayout", name = "constraintlayout-compose", version.ref = "constraintLayout" }

androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "androidxNavigation" }

androidx-test-ext = { group = "androidx.test.ext", name = "junit-ktx", version.ref = "androidxTestExt" }

androidx-test-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidxEspresso" }


coil-kt-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }

junit4 = { group = "junit", name = "junit", version.ref = "junit4" }

kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "datetime" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serialization" }

koin-android = { group = "io.insert-koin", name = "koin-android", version.ref = "koin" }
koin-compose = { group = "io.insert-koin", name = "koin-androidx-compose", version.ref = "koin" }


room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }

#youtubedl-android-library = { group = "com.github.yausername.youtubedl_android", name = "library", version.ref = "youtubedlAndroid" }
#youtubedl-android-ffmpeg = { group = "com.github.yausername.youtubedl_android", name = "ffmpeg", version.ref = "youtubedlAndroid" }
#youtubedl-android-aria2c = { group = "com.github.yausername.youtubedl_android", name = "aria2c", version.ref = "youtubedlAndroid" }

youtubedl-android-library = { group = "io.github.junkfood02.youtubedl-android", name = "library", version.ref = "youtubedlAndroid" }
youtubedl-android-ffmpeg = { group = "io.github.junkfood02.youtubedl-android", name = "ffmpeg", version.ref = "youtubedlAndroid" }
youtubedl-android-aria2c = { group = "io.github.junkfood02.youtubedl-android", name = "aria2c", version.ref = "youtubedlAndroid" }

mmkv = { group = "com.tencent", name = "mmkv", version.ref = "mmkv" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
android-test = { id = "com.android.test", version.ref = "androidGradlePlugin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
room = { id = "androidx.room", version.ref = "room" }
ktfmt-gradle = { id = "com.ncorti.ktfmt.gradle", version.ref = "ktfmt" }


[bundles]
accompanist = [
    "accompanist-permissions",
]

androidxCompose = ["androidx-compose-ui",
    "androidx-compose-ui-tooling-preview",
    "androidx-compose-material-iconsExtended",
    "androidx-compose-material3",
    "androidx-compose-material3-windowSizeClass",
    "androidx-compose-foundation",
    "androidx-navigation-compose",
    "androidx-compose-animation",
    "androidx-constraintlayout-compose",
    "androidx-compose-material"
]

youtubedlAndroid = ["youtubedl-android-library",
    "youtubedl-android-ffmpeg",
    "youtubedl-android-aria2c"]

core = ["androidx-activity-compose",
    "android-material",
    "androidx-appcompat",
    "androidx-core-ktx"]
